### ISSUE TITLE
The generation of published ''Pseduo-masks from classification phase''

### ISSUE THREAD

**Issue by Zhengyang1995** [XMed-Lab/URN#4]
Hey, thank you for your impressive works.
Would you please kindly give us an explanation to the published ''Pseduo-masks from classification phase''?

I guess it is the CAM generated from the trained classification network, and then post-processed by dCRF, finally with a threshold to distinguish background and certain class.
If the procedure is correct, would you please let me know the threshold between bg and fg? Or if there is anything different, please let me know.

Thank you so much!

**Comment by Zhengyang1995** [comment]
Or maybe there is no dCRF in that moment?

**Comment by Eli-YiLi** [comment]
> Hey, thank you for your impressive works. Would you please kindly give us an explanation to the published ''Pseduo-masks from classification phase''?
> 
> I guess it is the CAM generated from the trained classification network, and then post-processed by dCRF, finally with a threshold to distinguish background and certain class. If the procedure is correct, would you please let me know the threshold between bg and fg? Or if there is anything different, please let me know.
> 
> Thank you so much!

Your understanding is right, it comes from classification net with post-processing of PPMG with CRF.
