### ISSUE TITLE
About generate mask

### ISSUE THREAD

**Issue by ZechengLi19** [XMed-Lab/URN#6]
Thanks for your perfect work! Now I have a question. If I want to generate WSSS mask for coco dataset? Can I use the weight you provide directly? Which weight and config file, I should use? for res2net.
Thanks for helping!!!

**Comment by Eli-YiLi** [comment]
The intermediate weights are trained from voc dataset, and the weights of coco are missed.
You could train the segmentation model via the provided pseudo-mask from classification phase.
